// @generated
// This file is @generated by prost-build.
/// from substreams-spl’s MintOrBurnEvent
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MintOrBurnEvent {
    #[prost(string, tag="1")]
    pub mint: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub amount: u64,
    #[prost(bool, tag="4")]
    pub is_mint: bool,
}
// @@protoc_insertion_point(module)
