// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WormholeTokenTransfer {
    #[prost(string, tag="1")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub transfer_amount: u64,
    #[prost(string, tag="3")]
    pub asset_address: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub source_chain: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub recipient_address: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub target_chain: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub sender_address: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub block_time: u64,
    #[prost(uint64, tag="9")]
    pub block_height: u64,
    #[prost(uint32, tag="10")]
    pub sequence_number: u32,
    #[prost(string, tag="11")]
    pub token_symbol: ::prost::alloc::string::String,
    #[prost(uint32, tag="12")]
    pub token_decimals: u32,
    #[prost(string, tag="13")]
    pub token_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WormholeTokenTransfers {
    #[prost(message, repeated, tag="1")]
    pub transfers: ::prost::alloc::vec::Vec<WormholeTokenTransfer>,
}
// @@protoc_insertion_point(module)
